language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

# Build only master branch and version tags - http://stackoverflow.com/a/31882307/463761
branches:
  only:
    - master
    - /^v[0-9]/

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose

addons:
  apt:
    sources:
      - kalakris-cmake # provides cmake 2.8.11+ for libssh2-sys
    packages:
      - cmake # need cmake 2.8.11+ for libssh2-sys

notifications:
  email:
    on_success: never
